src/views/plugin/PluginCardListView.vue
=> fix no plugin installed empty page ui

package.json, src/views/discover/TorrentCardListView.vue
=> fix: 筛选出现的bug

src/@core/utils/formatters.ts, src/views/subscribe/FullCalendarView.vue
=> fix: 修复 tmdb 未记录发行日期的剧集全部堆叠在今天的问题

src/views/dashboard/AnalyticsMemory.vue
=> feat: 内存占用图使用百分比

src/@layouts/components/VerticalNav.vue
=> try fix bug

src/views/system/NameTestView.vue
- 如果应用了识别词，则显示应用详情（可展开）
- 如果没有应用识别词，则不显示，与之前相同
=> feat: 识别测试结果在应用识别词时显示应用详情

src/views/reorganize/TransferHistoryView.vue
=> feat 添加历史记录搜索提示

src/components/form/SubscribeEditForm.vue
=> feat 订阅增加保存路径设置

src/views/subscribe/FullCalendarView.vue
当订阅剧集过多时，把所有集单独展示会导致列表太长了
修改后pc端：
移动端加了角标：
=> feat:更改多集展示样式

src/plugins/vuetify/defaults.ts, src/styles/styles.scss, src/util/dom.ts, src/views/discover/TorrentCardListView.vue, src/views/discover/TorrentRowListView.vue, src/views/reorganize/TransferHistoryView.vue
fix:解决历史记录不居中的问题
change:历史历史错误信息使用tooltip展示
fix:解决当搜索结果过多导致页面卡顿问题
=> 解决bug和效果优化

src/components/FileBrowser.vue, src/views/reorganize/FileBrowserView.vue
=> fix: 文件管理初始化两次的bug

src/components/cards/SubscribeCard.vue
很多剧自动订阅的，订阅完想看看这剧的简介，刚好这也有人提了 https://github.com/jxxghp/MoviePilot/issues/1368
=> 订阅卡片增加剧集详情跳转功能

src/plugins/vuetify/defaults.ts
=> chore: add half-increments for v-rating

src/views/subscribe/FullCalendarView.vue
=> 设置每周一为第一天，当天背景突显

public/nginx.conf, public/service.js, src/views/setting/AccountSettingSite.vue
=> 支持本地CookieCloud服务器

package.json, src/api/types.ts, src/pages/login.vue, src/views/setting/AccountSettingAccount.vue, src/views/setting/AccountSettingSystem.vue, yarn.lock
=> feat #1763 用户可在个人设置中自行开启二次验证

src/@core/utils/compatibility.ts, src/views/reorganize/TransferHistoryView.vue
=> 低版本浏览器数组不支持at函数问题修复

src/views/reorganize/TransferHistoryView.vue
=> fix 历史记录分页相关错误

package.json, src/@core/utils/formatters.ts
issue94: 低版本Safari浏览器不能正确显示订阅的更新日期
采用dayjs进行处理时间
=> fix: 低版本Safari浏览器不能正确显示订阅的更新日期

src/views/setting/AccountSettingAccount.vue
- 修复 群晖套件添加用户功能无法使用域名代理，导致添加用户失败的问题
=> 修复 套件版本无法添加用户的问题

src/views/discover/TorrentCardListView.vue
显示性能优化，默认只显示前面20个，页面滚到底部才会再加载新的数据。
手动撸的，个人测试了下电脑端和安卓端，效果还是有的。苹果的没设备测试。
=> TorrentCardListView.vue 显示性能优化

src/views/dashboard/AnalyticsWeeklyOverview.vue
=> 优化 "最近入库" 数量显示

src/layouts/components/SearchBar.vue
- 在Vue组件的`script`部分，新增了`isMac`方法用于检测操作系统。
- 添加了计算属性`metaKey`，用于动态生成按键提示。
- 修改了模板部分的按键提示显示逻辑，使用计算属性`metaKey`。
=> 实现根据操作系统动态显示不同的搜索快捷键提示

src/components/cards/FilterRuleCard.vue
- 兼容规则中存在多余空格或换行符的场景
- 增加 cleanedRules 用于清洗规则
=> fix(FilterRuleCard): 移除规则中的空白字符并保留前后的空格

src/main.ts
- fix build error like `ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)`
=> fix(build): wrap top-level await in async function for browser compatibility

index.html
- 目前Nginx中配置为no-cache，移除不必要的预加载，避免重复加载两次资源
=> chore: remove unnecessary preload for index.js

src/components/cards/StorageCard.vue
优化进度条和剩余存储空间的显示。统一为与阿里云盘、115网盘显示格式相同。
=> style: Optimize the progress bar and the display of remaining storage space.

src/components/cards/CustomRuleCard.vue, src/components/cards/DownloaderCard.vue, src/components/cards/FilterRuleGroupCard.vue, src/components/cards/MediaServerCard.vue, src/views/setting/AccountSettingRule.vue, src/views/setting/AccountSettingSystem.vue
调整部分样式，并给下载器、媒体服务器、自定义规则、优先级规则组，名称与ID增加重名警告和空值警告
=> feat: Add duplicate name judgment and null value judgment

src/components/dialog/UserAddEditDialog.vue
隐藏已有用户二次编辑中的用户名；补全新增用户界面的默认头像显示；增加分割线。
=> style: User style adjustment

src/components/cards/UserCard.vue, src/components/dialog/UserAddEditDialog.vue, src/layouts/components/UserProfile.vue
=> fix: handle scenarios where avatar is empty
